Remove i386 from composer
It's been failing to build for a while:

    + apk add --no-cache --virtual .composer-rundeps p7zip bash coreutils git make mercurial openssh-client patch subversion tini unzip zip
    fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86/APKINDEX.tar.gz
    fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86/APKINDEX.tar.gz
    ERROR: unable to select packages:
      mercurial (no such package):
        required by: .composer-rundeps-20211119.213859[mercurial]